version: "3.7"

services:
  store-management:
    depends_on:
      - mysql
    restart: on-failure
    image: "{DOCKER_CREDS_USR}/sm:${BUILD_ID}"
    ports:
      - 8088:8080
    environment:
      SPRING_DATASOURCE_URL:  jdbc:mysql://mysql:3306/store?createDatabaseIfNotExist=true

  mysql:
    image: mysql:5.7
    ports:
      - 3331:3306
    volumes:
      - mysql-data-compose:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

volumes:
  mysql-data-compose:
